### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by niccolofiaschi** [Cyberfly100/Pfeiffer-TC110#1]
Hi,
I would like to use this package since looks perfect!
however i am a bit puzzled with the connection from the computer to the controller. Which USB to RS485 converter you use? do you also leave the DCU controller from pfeiffer connected via a Y connector M12 or you only connect the TC110 a the computer?
I would like to avoid frying the pump-station :)
Best,
Nicco

**Comment by Cyberfly100** [comment]
I was using Pfeiffer's PM 061 207 -T USB to RS485 connector. I have not done a good job documenting how I connected everything in the end but I will try to reach out to people who might be able to find out. I remember that despite the y-splitter I could not use the display of the pump at the same time as the remote control. I therefore programmed a kivy GUI and ran it on a Raspberry Pi with a touchscreen. I can maybe dig up this code somewhere if you are interested. We were using an analog gauge to read the pressure so a analog to digital converter is needed. I am trying to remember if I was using reading the pressure via the Pfeiffer controller somehow....but my feeling is no. Maybe I was waiting for a ADC shield to arrive and that took forever.
I will try to research a bit and get back to you.

**Comment by niccolofiaschi** [comment]
Thanks so much!

**Comment by Cyberfly100** [comment]
An RS485 bus can only have one master, which is why you can not connect both the PC and the Pfeiffer display and control unit (DCU). I used the Y-splitter as a gender changer to connect an M12 cable between the TC110 and the USB converter. But if you just get the right cable in the first place that should not be necessary 😁.

**Comment by Cyberfly100** [comment]
@niccolofiaschi: any success trying this out?

**Comment by niccolofiaschi** [comment]
Hey,
not that much. I got the proper cables from Pfeiffer but I never spent time to connect it to the PC (was not plug and play definitely). At the end we finished that project quite early so was not worth to go crazy on it :)
thanks a lot!!!

**Comment by Cyberfly100** [comment]
Ok. No worries. Let me know if you want to give it another go.
